### ISSUE TITLE
foutmelding op item pagina

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#1]
Ik vermoed iets te maken met de afbeelding. Bij het opladen van een nieuwe afbeelding krijg ik ook een foutmelding. 

![capture](https://cloud.githubusercontent.com/assets/3798589/20672001/fd2bc01c-b57f-11e6-86ac-a58888cd780c.JPG)

**Comment by JorisLambrechts** [comment]
de instellingen van de open layers plugin stonden nog niet juist
