### ISSUE TITLE
image FL ID niet opgehaald

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#14]
De FL ID wordt wel toegevoegd, maar de image wordt niet opgehaald. Je blijft de cover zien. Misschien een verkeerde request naar de resolver?

![image](https://user-images.githubusercontent.com/3798589/27678640-34415e1c-5cb6-11e7-9acf-a3b76e458410.png)

**Comment by roxannewyns** [comment]
test item = 133

**Comment by JorisLambrechts** [comment]
Er is blijkbaar iets mis in de resolver, als je die naar die resolver.libis/FL-nummer gaat krijg je de cover, maar als je daar stream?quality=low achter zet krijg je wel de juiste afbeelding. Er zijn dus volgens mij geen thumbnails gemaakt voor die FL's.

vb. http://resolver.libis.be/FL8882400 en http://resolver.libis.be/FL8882400/stream?quality=low
