### ISSUE TITLE
vakjes moet allemaal even groot

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#16]
vakjes even groot maken voor tentoonstellingen, projecten, showcases.
Indien probleem met cropping, kan je me de exacte size doorgeven en dan zeg ik hen dat ze zelf beelden van dat formaat moeten opladen. 

![image](https://user-images.githubusercontent.com/3798589/28173211-ff712512-67ed-11e7-8da2-e8078531bb2c.png)

**Comment by JorisLambrechts** [comment]
Het formaat is niet belangrijk (Omeka maakt er zelf de juiste versies van) maar de verhouding lengte-breedte moet wel altijd hetzelfde zijn (vb. 3 breedte en 2 hoogte of omgekeerd).

Hier gebruiken ze vierkanten: https://krollermuller.nl/visit
En hier gebruiken ze 2 hoog en 3 breed of iets dat er op lijkt: https://www.vangoghmuseum.nl/nl/ontdek-de-collectie

Mij maakt het niet uit wat ze kiezen, maar het moet wel altijd hetzelfde zijn.

**Comment by roxannewyns** [comment]
UBD wil de afbeeldingen naar het voorbeeld van https://www.vangoghmuseum.nl/nl/ontdek-de-collectie
Het tekstvak eronder moet samen met het beeld een vierkant vormt. UBD zal naar de invoerders instructies geven over het aantal woorden / tekens voor het tekstvak om het vierkant niet te overschrijden.
