### ISSUE TITLE
source verchillende keren toegevoegd

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#23]
Om een of andere reden wordt source bij dit item meerdere keren herhaald. Weet niet of het ook bij andere een probleem is en of het dus aan de mapping of aan het recor ligt. 
Er moet hier waarschijnlijk ook nog een concordantielijst komen voor omzetting van de codes in tekst zoals bij lectio en lovaniensia het geval is. 
ub_digitaal/admin/items/edit/853

**Comment by JorisLambrechts** [comment]
De source en de callnumber komen momenteel uit de holdings. En dit item heeft er 17.

Misschien moeten we dus inderdaad een ander veld gebruiken voor de bron.
