### ISSUE TITLE
resolutie in Omeka toegevoegde beelden niet altijd hoog genoeg om in te zoomen

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#24]
e.g. ub_digitaal/items/show/853 en /items/show/73

Ik denk dat we een hoge resolutie moeten tonen.

**Comment by roxannewyns** [comment]
Hogere resolutie ophalen uit Rosetta. /stream?quality=high
Er moet ook nog een link naar het object in de viewer toegevoegd worden in het metadata record. IE/representation

**Comment by JorisLambrechts** [comment]
- item 73 komt niet uit de resolver dus daar kunnen we zelf niet veel aan doen. De originele afbeeldingen zijn is ook maar rond de 800px groot. 
- item 853 verwijst naar resolver.libis.be/IE2634494/stream en dat geeft een html file vandaar dat de import er op vast loopt

/stream?quality=high kunnen we niet gebruiken want Omeka kan geen jp2 converteren naar jpeg maar quality=low is ook meer dan groot genoeg (vb. http://resolver.libis.be/IE4712529/stream?quality=low). 

Verder heb ik de maximum import resolutie verhoogt naar 1500px (langste zijde) en de zoomfunctie wat aangepast zodat er verder kan ingezoomed worden (vermoedelijk was dat het probleem).
