### ISSUE TITLE
mapping nakijken of alles meekomt

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#25]
opmerking dat niet alle gevraagde metadata overgezet wordt van Alma naar Omeka
nakijken of alles in mapping zit. metadata overzicht zit in map op l schijf onder projecten > heron > ub

**Comment by roxannewyns** [comment]
[Alma-omeka mapping template.xlsx](https://github.com/libis/UB-digitalisering-omeka/files/1676788/Alma-omeka.mapping.template.xlsx)

Mappingtabel. Checken of alles ewerd toegevoegd in Alma sync.

**Comment by JorisLambrechts** [comment]
dit is in orde, alles komt mee
