### ISSUE TITLE
Design home page

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#26]
Uitlijnen tekst/link 'Bekijk tentoonstelling' zodat die allemaal op 1 lijn staat. Mag onderaan staan. Dit ook voor de blokjes Recente projecten en Showcases. 
![image](https://user-images.githubusercontent.com/3798589/35521228-7b154590-0519-11e8-8f83-ce5d6ae1ebd4.png)

Tekst aanpassen bij Recente projecten in 'Bekijk projecten' i.p.v. 'Bekijk tentoonstelling'. 
![image](https://user-images.githubusercontent.com/3798589/35521402-ec9a45f8-0519-11e8-9123-319ebb69b22b.png)

Derde afbeelding home page is minder hoog dan 1ste en 2de. Ik zou die de beelden (en kolom) allemaal dezelfde afmeting geven. 
![image](https://user-images.githubusercontent.com/3798589/35521722-c37b0c9c-051a-11e8-9600-16ed95320ae9.png)

**Comment by JorisLambrechts** [comment]
https://github.com/libis/UB-digitalisering-omeka/commit/53750d848908742d027a6bf40e4518bcadf935a2
