### ISSUE TITLE
Banner aanpassen van tentoonstelling

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#28]
Net als bij KADOC willen ze de banner van een tentoonstelling kunnen aanpassen door een afbeelding op te laden in de image manager met als filename de slug. Misschien best ook in een aparte directory 'banners tentoonstellingen' of zoiets groeperen.

**Comment by JorisLambrechts** [comment]
De banners moeten in de map /exhibits komen met naam <slug>.jpg (vb 500-jaar-dodoens.jpg)

**Comment by roxannewyns** [comment]
als je .JPG gebruikt werkt het niet. Kan je dat aanpassen zodat zowel .jpg als .JPG werken? Indien lastig, sluit dit dan maar weer.

**Comment by JorisLambrechts** [comment]
je kan de JPG ook omzetten naar jpg in de ImageManager (gewoon via 'rename'). Dat is nog het simpelste.
