### ISSUE TITLE
search for child objects geeft foutmelding

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#3]
![capture](https://cloud.githubusercontent.com/assets/3798589/23938205/9d209d48-095b-11e7-9182-63392c9d1255.JPG)

**Comment by JorisLambrechts** [comment]
De resultaten van de resolver zijn wat anders blijkbaar. in de json zit nu nog een REPxxxxxx achter de IE-nummer en dan pas de FL-nummers. Ik zal de plugin herwerken.

**Comment by JorisLambrechts** [comment]
fixed in https://github.com/libis/UB-digitalisering-omeka/commit/b84479253f4ddd771657606a92adf28c8982a10c
