### ISSUE TITLE
Pop-up lightbox afbeelding

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#30]
navigatiepijltjes om naar volgende afbeelding te gaan en X om box te sluiten ontbreken 

![image](https://user-images.githubusercontent.com/3798589/35525550-187448a8-0525-11e8-9773-2a7134b74ae6.png)

**Comment by JorisLambrechts** [comment]
ok, moest de afbeeldingen nog uploaden
