### ISSUE TITLE
Tentoonstelling - gallerij

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#33]
In dit voorbeeld (/show/500-jaar-dodoens/tijdgenoten/fuchs) werden 3 afbeeldingen opgeladen. De 3de afbeelding zou gecentreerd moeten staan. 
![image](https://user-images.githubusercontent.com/3798589/35526845-18ed6216-0529-11e8-9015-b9a6767c9d96.png)

**Comment by JorisLambrechts** [comment]
Dat is onmogelijk in deze structuur, ofwel worden ze geschraagd getoond (valt hier niet op omdat ze allemaal dezelfde hoogte hebben) ofwel gecentreerd.
