### ISSUE TITLE
aantal afbeeldingen per item

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#36]
Momenteel is het max. aantal afbeeldingen per item gelimiteerd op 20. Kan dit verhoogd worden?

**Comment by JorisLambrechts** [comment]
Er is geen limiet op afbeeldingen per item. Ik heb er net 21 in één keer toegevoegd aan een item en dat ging zonder problemen.

Misschien was één van de files te groot, in de volgende deployment zal ik de maxFileSize verhogen.
