### ISSUE TITLE
metadata item

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#38]
in item metadata moet ook link naar record in Limo, link naar afbeelding in viewer opgenomen worden.

**Comment by JorisLambrechts** [comment]
dit is intussen in orde, ik heb alle velden nagekeken: http://heron-net.be/ub_digitaal/items/show/271

**Comment by JorisLambrechts** [comment]
Er moet wel opnieuw geïmporteerd worden om alle metadata te krijgen
