### ISSUE TITLE
afmetingen afbeelding banner, kaders etc

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#39]
Kan je de afmeting van de banner, de kaders en blokjes bezorgen.

![image](https://user-images.githubusercontent.com/3798589/35556116-a8fcdddc-05a1-11e8-80ce-d573e0bbbf81.png)
![image](https://user-images.githubusercontent.com/3798589/35556117-aba17b7e-05a1-11e8-8727-b71e2b2ab695.png)

**Comment by JorisLambrechts** [comment]
- De afbeeldingen op de homepage moeten minsten 600px op 350px zijn. Deze hangen niet aan een item maar staan gewoon in de image folder. Ze mogen groter zijn, maar dan wel in ongeveer dezelfde verhouding.
- De afbeeldingen voor de blokjes zijn de cover-images van de exhibits die ik vervolgens als achtergrond gebruik (hangt dus wel aan een item) in een kader met verhouding 3 breed en 2 hoog. Het is dus ook dezelfde afbeelding als die op de overzichtspagina van een tentoonstelling. Aangezien ze op 2 verschillende plaatsen gebruikt worden is het moeilijk om vaste afmetingen te geven. Verhouding 3 op 2 is ideaal voor de blokjes maar dan heb je op de overzichtspagina een kleinere (geen lange) afbeelding. Als het een afbeelding met portretverhouding is wordt dus het midden van de afbeelding getoond zoals nu op de website (valt meestal wel goed mee).
