### ISSUE TITLE
bij toevoegen van IE Just fill in the pid (if known) krijg je connectio was reset

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#4]
Bij toevoegen van IE of FL id aan "Just fill in the pid (if known)." krijg je connection was reset. Als je dan je scherm refreshed, ga je terug naar het item record en dan is de afbeelding 2 x toegevoegd aan het record.

**Comment by JorisLambrechts** [comment]
solr was niet correct geconfigureerd waardoor er bij het saven van records vanalles fout liep
