### ISSUE TITLE
Showcases

### ISSUE THREAD

**Issue by roxannewyns** [libis/UB-digitalisering-omeka#42]
Kader op de 2de lijn kleiner dan die op 1st lijn. 

![image](https://user-images.githubusercontent.com/3798589/35971358-fe879548-0ccd-11e8-92ea-b9bb82754f28.png)

**Comment by JorisLambrechts** [comment]
Dit komt door het ontbreken van de afbeelding. Ik heb die test-showcases verwijderd. Verder moet er altijd een afbeelding als cover gekozen worden of op de eerste pagina een afbeeldingen gebruikt worden.
